#!/bin/sh

# Get list of mounted USB-connected block devices. Comando gerado no claude
choice=$(lsblk -o NAME,SIZE,MOUNTPOINT,TRAN | awk '/usb/ {usb=1; next} usb && /└─|├─/ && $3 {gsub(/[└├]─/, "", $1); print "/dev/"$1" ("$2")"}' | dmenu -i  -p unmount)

if [ -z "$choice" ]; then
  # Empty variable
    exit 1
else
    #udisksctl unmount -b $choice
    output=$(udisksctl unmount -b $choice 2>&1 | sed 's/"/\\"/g')
    ratpoison -c "echo \"$output\""
fi
